### ISSUE TITLE
Vendor javascript missing from the dockerfile

### ISSUE THREAD

**Issue by aconite33** [bitwarden/web#1543] opened 2022-03-15 13:29 UTC
### Steps To Reproduce

1. Download the setup file for the docker
2. Execute the script to install and start up the docker images.
3. Verify that once the install is complete, the vendorXXX.js file is missing
4. Confirm that you cannot log into the Bitwarden portal due to the 404.

### Expected Result

You should be able to get the login prompt on the website.

### Actual Result

A 404 happens and you end up with a endless circle loading screen.

### Screenshots or Videos

![Screenshot from 2022-03-14 08-03-40](https://user-images.githubusercontent.com/3675886/158388044-4cfbe2d2-7e57-41c7-8726-e7da5a6cf1c8.png)

### Additional Context

This can be remediated by download the vendor javascript file from: `https://vault.bitwarden.com/app/vendor.7f0a909b78a411824308.js` and putting it into the docker file under `/app/app` file.

### Operating System

Linux

### Operating System Version

Ubuntu 20.04

### Web Browser

Chrome

### Build Version

1.46.2

**Comment by Hinton** [comment] 2022-03-21 10:59
Can you provide some additional information on how to replicate this issue @aconite33?

Running `docker run -it --entrypoint sh bitwarden/web:2.26.1`, and `ls app` outputs the following files
```sh
main.70e6ec4e17a466ff6daf.js       polyfills.3ab3aecac16277160ac5.js.LICENSE.txt
main.70e6ec4e17a466ff6daf.js.map   polyfills.3ab3aecac16277160ac5.js.map
main.7b7aed24fb95652a39f4.css      vendor.7f0a909b78a411824308.js
main.7b7aed24fb95652a39f4.css.map  vendor.7f0a909b78a411824308.js.LICENSE.txt
polyfills.3ab3aecac16277160ac5.js  vendor.7f0a909b78a411824308.js.map
```

**Comment by aconite33** [comment] 2022-03-21 12:04
I followed the instructions here: https://bitwarden.com/help/install-on-premise-linux/

Here is what I have when I step inside our running web docker:

![image](https://user-images.githubusercontent.com/3675886/159257331-0bbc76b0-df6a-405a-b182-1cd6e3e3482a.png)

I have to download the vendor javascript file and insert it into the docker file.

**Comment by Hinton** [comment] 2022-03-22 10:21
That's weird.

I wonder if re-creating the web container would work. Could you try running the same commands as I did above and check if the file exists there?

```
docker run -it --entrypoint sh bitwarden/web:2.26.1
ls app
```

**Comment by aconite33** [comment] 2022-03-28 13:21
Running:

```
docker run -it --entrypoint sh bitwarden/web:2.26.1
ls app
```

Results in the same issue. No vendor.js supplied.

Even executing docker-compose up --build, I cannot get to pull the vendor.js file appropriately.

However, using the script with `rebuild` option worked. (Can't believe I missed this).

I can confirm that the vendorjs is now sitting there. I will update after I leave it running for a few days. We didn't have any issues when we first setup on prem, but only had this after the docker had been running for a few days.

**Comment by Hinton** [comment] 2022-03-28 14:09
It sounds odd. Nice that `rebuild` worked but has me confused as to why the vendor file would disappear.

**Comment by aconite33** [comment] 2022-03-28 14:14
I agree. I'll monitor it for a few days and if it happens again, I'll post back here.

If it goes a week or so without issue, I believe we can close it. I do know that I first started encountering it after I did a upgrade command via the script.

**Comment by djsmith85** [comment] 2022-04-06 21:48
@aconite33 I'm closing this now. 
If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-04-06 21:48 UTC
Labels: bug
