### ISSUE TITLE
[2.17.1]  Password exports are misleading in some cases

### ISSUE THREAD

**Issue by dwarf-king-hreidmar** [bitwarden/web#795] opened 2021-01-21 03:53 UTC
## Export contains inaccurate / old passwords from before they were added to org.

When exporting passwords for my user I found entries that had been shared with an organization but with outdated information (wrong username or password). I could export the org and get the correct un/pw. I only noticed this because I was using grep on the user export to confirm passwords I expected to be there. I also noticed that the shared passwords appearing in the export were not actually displayed in my account on git web.

## Steps To Reproduce
1. Create some passwords.
2. Share them with an ORG
4. Export a user's passwords
5. Export the org's passwords
6. Note entries with the same website but different ID and wrong u/n password..

## Expected Result
Either export org owned passwords that the user originally owned or don't export them at all. Do not export pw that aren't visible to the user in the UI.

## Actual Result

Entries for the same site exist in both exports but one is wrong.

##Notes
I may be assuming too much here. Could be that the bug is actually erased an entry and created a new one and then shared it with a org. However, I have to wonder why I can only find the org version in the gui but the export contains entries with bad u/n or p/w.

## Environment

- Operating system: Linux
- Browser: Firefox
- Build Version (Bottom of the page): [2.17.1]

**Comment by mobamoba** [comment] 2021-02-03 16:29
Just adding a "me too" on this. The UI shows me around 80 passwords and the export did over 1000. Those 1000 had been deleted months ago yet all of them showed up in the JSON file and I have no idea how to get just the 80 that show in UI.

**Comment by cscharf** [comment] 2021-02-03 17:48
@dwarf-king-hreidmar & @mobamoba , were the entries you're seeing still located in your 🗑️  `trash` folder?

**Comment by mobamoba** [comment] 2021-02-03 18:02
Yes, but when imported, they wound up in the "No Folder" folder as opposed to in the Trash folder.

**Comment by cscharf** [comment] 2021-02-03 20:30
yeah, we don't add any flags/indicators on export that an item was in trash; that's expected behavior (at least working as programmed). The latest version of the web client should be fixed to no longer export items from trash (negating the re-import of those): https://github.com/bitwarden/jslib/pull/241.

Can you please indicate whether this is still happening on export of v2.18.1

**Comment by mobamoba** [comment] 2021-02-03 21:29
Ah I see. And I came up with my own workaround (moving my real passwords to a folder before exporting then deleting everything in the No Folder folder afterwards). Also, I don't mind having all those old passwords in the Trash because it's possible I deleted something by mistake, so for me, I actually prefer the current version that exports everything - even if I have to do a bit of extra make-work - rather than the new version that ignores Trash.

**Comment by cscharf** [comment] 2021-02-03 21:32
Keep in mind we do have plans in the future to make trash a temporary location (i.e. after 30 days items in trash are deleted, etc.) We haven't implemented this yet, but as space requirements start filling up we put that notice out there just so nobody is under the false security that the trash is a folder, it's actually a soft-deleted flag (via a date) that's treated differently than other items (not a folder) and we will likely roll something out in the future like many other cloud services that deletes those items in the trash bin after a certain time frame.

**Comment by mobamoba** [comment] 2021-02-03 21:43
Okay thanks - I've been using it like an archive folder because with passwords better safe than sorry. I'm self-hosted so space isn't a concern; would it be possible to allow "perma-trash" for those of us not using the cloud?

**Comment by cscharf** [comment] 2021-02-03 21:50
> I'm self-hosted so space isn't a concern; would it be possible to allow "perma-trash" for those of us not using the cloud?

We'll take that into consideration when or if we create a cleanup job, to ensure it can be made optional via runtime-environment configuration.

@dwarf-king-hreidmar , closing this issue for now as it appears the latest version of the web vault resolves it, but please feel free to re-open it if this continues to be an issue.

**Closed by cscharf** 2021-02-03 21:50 UTC

**Comment by dwarf-king-hreidmar** [comment] 2021-02-08 04:01
I can confirm this was fixed in 2.18.1. Thanks so much folks!
