### ISSUE TITLE
Importing a CSV with password with character length greater than 1000 breaks user import flow

### ISSUE THREAD

**Issue by JohnMcLear** [bitwarden/web#837] opened 2021-02-19 10:43 UTC
In bitwarden.com the user flow for importing CSV can get broken too easily.  This is due to a confusing error message on import.

Todo:

- [ ] Clarify if this is ``password`` only or if the 1000 characters applies to the entire entry.
- [ ] Train customer service / twitter account personel to understand what this import message means and instead of recommending purchasing premium to point them to a support thread.
- [ ] Update the docs on the import page with some common faults/troubleshooting steps.
- [ ] change language on the 1000+ chars error, it should provide steps to remedy the problem IE "Find the line in your CSV with a password character count length greater than 1000 and remove it. ``=LEN()`` will show you character Length in most spreadsheet applications" <-- quick win that will resolve majority of the issues.
- [ ] import ALL other items but display a huge warning saying we didn't import item of ``url`` because it's password length was too long.  Please do this one manually. <-- more work but a better UX - it's likely < 1% of passwords will be greater than 1000 characters.

Breadcrumbs and context is available here: https://twitter.com/java2107/status/1362708042933018626

**Comment by cscharf** [comment] 2021-02-19 16:12
Thanks @JohnMcLear , while I'm closing this as a duplicate of https://github.com/bitwarden/web/issues/102 which we're actively working on, I'll add this feedback on our internal tracking system and link here so the developer working on it has some additional reference. I'll also pass along your feedback to our Customer Success team.

**Closed by cscharf** 2021-02-19 16:12 UTC
