### ISSUE TITLE
"Accepted" tab within an organization cannot be opened.

### ISSUE THREAD

**Issue by Dennis14e** [bitwarden/web#632] opened 2020-09-03 09:35 UTC
## Describe the Bug

When I try to open the "Accepted" ("Akzeptiert" in german) tab under "Manage" ("Verwalten") within an organization, it does not open and errors appear in the browser console.

## Steps To Reproduce

1. Open an organisation (as administrator)
2. Go to "Manage" ("Verwalten" in german)
3. Go to "People" ("Leute")
4. Click on the "Accepted" ("Akzeptiert") tab

## Expected Result

The content of the tab opens.

## Actual Result

The tab does not open and the following errors appear in the browser console:

```
vendor.44503f821bca8b2d0c85.js:566 ERROR TypeError: Cannot read property 'length' of undefined
    at n.isPaging (main.44503f821bca8b2d0c85.js:1)
    at Object.updateDirectives (main.44503f821bca8b2d0c85.js:1)
    at Object.updateDirectives (vendor.44503f821bca8b2d0c85.js:806)
    at fb (vendor.44503f821bca8b2d0c85.js:799)
    at _b (vendor.44503f821bca8b2d0c85.js:799)
    at kb (vendor.44503f821bca8b2d0c85.js:799)
    at fb (vendor.44503f821bca8b2d0c85.js:799)
    at _b (vendor.44503f821bca8b2d0c85.js:799)
    at wb (vendor.44503f821bca8b2d0c85.js:799)
    at fb (vendor.44503f821bca8b2d0c85.js:799)
np @ vendor.44503f821bca8b2d0c85.js:566
e.handleError @ vendor.44503f821bca8b2d0c85.js:573
(anonymous) @ vendor.44503f821bca8b2d0c85.js:638
t.invoke @ polyfills.44503f821bca8b2d0c85.js:8
e.run @ polyfills.44503f821bca8b2d0c85.js:8
e.runOutsideAngular @ vendor.44503f821bca8b2d0c85.js:624
e.tick @ vendor.44503f821bca8b2d0c85.js:638
(anonymous) @ vendor.44503f821bca8b2d0c85.js:638
t.invoke @ polyfills.44503f821bca8b2d0c85.js:8
onInvoke @ vendor.44503f821bca8b2d0c85.js:624
t.invoke @ polyfills.44503f821bca8b2d0c85.js:8
e.run @ polyfills.44503f821bca8b2d0c85.js:8
e.run @ vendor.44503f821bca8b2d0c85.js:624
next @ vendor.44503f821bca8b2d0c85.js:638
i @ vendor.44503f821bca8b2d0c85.js:431
t.__tryOrUnsub @ vendor.44503f821bca8b2d0c85.js:1389
t.next @ vendor.44503f821bca8b2d0c85.js:1389
t._next @ vendor.44503f821bca8b2d0c85.js:1389
t.next @ vendor.44503f821bca8b2d0c85.js:1389
t.next @ vendor.44503f821bca8b2d0c85.js:1474
t.emit @ vendor.44503f821bca8b2d0c85.js:431
pf @ vendor.44503f821bca8b2d0c85.js:624
mf @ vendor.44503f821bca8b2d0c85.js:624
onInvokeTask @ vendor.44503f821bca8b2d0c85.js:624
t.invokeTask @ polyfills.44503f821bca8b2d0c85.js:8
e.runTask @ polyfills.44503f821bca8b2d0c85.js:8
e.invokeTask @ polyfills.44503f821bca8b2d0c85.js:8
b @ polyfills.44503f821bca8b2d0c85.js:39
m @ polyfills.44503f821bca8b2d0c85.js:39
vendor.44503f821bca8b2d0c85.js:566 ERROR TypeError: Cannot read property 'length' of undefined
    at n.isPaging (main.44503f821bca8b2d0c85.js:1)
    at Object.updateDirectives (main.44503f821bca8b2d0c85.js:1)
    at Object.updateDirectives (vendor.44503f821bca8b2d0c85.js:806)
    at fb (vendor.44503f821bca8b2d0c85.js:799)
    at _b (vendor.44503f821bca8b2d0c85.js:799)
    at kb (vendor.44503f821bca8b2d0c85.js:799)
    at fb (vendor.44503f821bca8b2d0c85.js:799)
    at _b (vendor.44503f821bca8b2d0c85.js:799)
    at wb (vendor.44503f821bca8b2d0c85.js:799)
    at fb (vendor.44503f821bca8b2d0c85.js:799)
np @ vendor.44503f821bca8b2d0c85.js:566
e.handleError @ vendor.44503f821bca8b2d0c85.js:573
(anonymous) @ vendor.44503f821bca8b2d0c85.js:638
t.invoke @ polyfills.44503f821bca8b2d0c85.js:8
e.run @ polyfills.44503f821bca8b2d0c85.js:8
e.runOutsideAngular @ vendor.44503f821bca8b2d0c85.js:624
e.tick @ vendor.44503f821bca8b2d0c85.js:638
(anonymous) @ vendor.44503f821bca8b2d0c85.js:638
t.invoke @ polyfills.44503f821bca8b2d0c85.js:8
onInvoke @ vendor.44503f821bca8b2d0c85.js:624
t.invoke @ polyfills.44503f821bca8b2d0c85.js:8
e.run @ polyfills.44503f821bca8b2d0c85.js:8
e.run @ vendor.44503f821bca8b2d0c85.js:624
next @ vendor.44503f821bca8b2d0c85.js:638
i @ vendor.44503f821bca8b2d0c85.js:431
t.__tryOrUnsub @ vendor.44503f821bca8b2d0c85.js:1389
t.next @ vendor.44503f821bca8b2d0c85.js:1389
t._next @ vendor.44503f821bca8b2d0c85.js:1389
t.next @ vendor.44503f821bca8b2d0c85.js:1389
t.next @ vendor.44503f821bca8b2d0c85.js:1474
t.emit @ vendor.44503f821bca8b2d0c85.js:431
pf @ vendor.44503f821bca8b2d0c85.js:624
mf @ vendor.44503f821bca8b2d0c85.js:624
onInvoke @ vendor.44503f821bca8b2d0c85.js:624
t.invoke @ polyfills.44503f821bca8b2d0c85.js:8
e.runGuarded @ polyfills.44503f821bca8b2d0c85.js:8
t @ polyfills.44503f821bca8b2d0c85.js:8
r.microtaskDrainDone @ polyfills.44503f821bca8b2d0c85.js:8
y @ polyfills.44503f821bca8b2d0c85.js:8
e.invokeTask @ polyfills.44503f821bca8b2d0c85.js:8
b @ polyfills.44503f821bca8b2d0c85.js:39
m @ polyfills.44503f821bca8b2d0c85.js:39
Show 2 more frames
vendor.44503f821bca8b2d0c85.js:566 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at n.loadMore (main.44503f821bca8b2d0c85.js:1)
    at n.<anonymous> (main.44503f821bca8b2d0c85.js:1)
    at main.44503f821bca8b2d0c85.js:1
    at Object.next (main.44503f821bca8b2d0c85.js:1)
    at main.44503f821bca8b2d0c85.js:1
    at new t (polyfills.44503f821bca8b2d0c85.js:8)
    at t (main.44503f821bca8b2d0c85.js:1)
    at n.resetPaging (main.44503f821bca8b2d0c85.js:1)
    at n.filter (main.44503f821bca8b2d0c85.js:1)
    at Object.handleEvent (main.44503f821bca8b2d0c85.js:1)
    at j (polyfills.44503f821bca8b2d0c85.js:8)
    at new t (polyfills.44503f821bca8b2d0c85.js:8)
    at t (main.44503f821bca8b2d0c85.js:1)
    at n.resetPaging (main.44503f821bca8b2d0c85.js:1)
    at n.filter (main.44503f821bca8b2d0c85.js:1)
    at Object.handleEvent (main.44503f821bca8b2d0c85.js:1)
    at Object.handleEvent (vendor.44503f821bca8b2d0c85.js:799)
    at Object.handleEvent (vendor.44503f821bca8b2d0c85.js:806)
    at lg (vendor.44503f821bca8b2d0c85.js:726)
    at vendor.44503f821bca8b2d0c85.js:734
np @ vendor.44503f821bca8b2d0c85.js:566
e.handleError @ vendor.44503f821bca8b2d0c85.js:573
next @ vendor.44503f821bca8b2d0c85.js:638
i @ vendor.44503f821bca8b2d0c85.js:431
t.__tryOrUnsub @ vendor.44503f821bca8b2d0c85.js:1389
t.next @ vendor.44503f821bca8b2d0c85.js:1389
t._next @ vendor.44503f821bca8b2d0c85.js:1389
t.next @ vendor.44503f821bca8b2d0c85.js:1389
t.next @ vendor.44503f821bca8b2d0c85.js:1474
t.emit @ vendor.44503f821bca8b2d0c85.js:431
(anonymous) @ vendor.44503f821bca8b2d0c85.js:624
t.invoke @ polyfills.44503f821bca8b2d0c85.js:8
e.run @ polyfills.44503f821bca8b2d0c85.js:8
e.runOutsideAngular @ vendor.44503f821bca8b2d0c85.js:624
onHandleError @ vendor.44503f821bca8b2d0c85.js:624
t.handleError @ polyfills.44503f821bca8b2d0c85.js:8
e.runGuarded @ polyfills.44503f821bca8b2d0c85.js:8
t @ polyfills.44503f821bca8b2d0c85.js:8
r.microtaskDrainDone @ polyfills.44503f821bca8b2d0c85.js:8
y @ polyfills.44503f821bca8b2d0c85.js:8
e.invokeTask @ polyfills.44503f821bca8b2d0c85.js:8
b @ polyfills.44503f821bca8b2d0c85.js:39
m @ polyfills.44503f821bca8b2d0c85.js:39
2vendor.44503f821bca8b2d0c85.js:566 ERROR TypeError: Cannot read property 'length' of undefined
    at n.isPaging (main.44503f821bca8b2d0c85.js:1)
    at Object.updateDirectives (main.44503f821bca8b2d0c85.js:1)
    at Object.updateDirectives (vendor.44503f821bca8b2d0c85.js:806)
    at fb (vendor.44503f821bca8b2d0c85.js:799)
    at _b (vendor.44503f821bca8b2d0c85.js:799)
    at kb (vendor.44503f821bca8b2d0c85.js:799)
    at fb (vendor.44503f821bca8b2d0c85.js:799)
    at _b (vendor.44503f821bca8b2d0c85.js:799)
    at wb (vendor.44503f821bca8b2d0c85.js:799)
    at fb (vendor.44503f821bca8b2d0c85.js:799)
```

## Environment

- Operating system: Manjaro Linux
- Browser: Google Chrome 85.0.4183.83
- Build Version (Bottom of the page): 2.15.1

**Comment by Greenderella** [comment] 2020-09-03 10:16
I can confirm this error. This has been forwarded to our development team for further investigation, thanks for the report.

**Comment by cscharf** [comment] 2020-09-03 13:50
Hi @Dennis14e , thank you for reporting this, as it turns out this is an existing (somewhat duplicate) issue and has the same root cause as https://github.com/bitwarden/web/issues/583, this has also been resolved and the fix will be released soon.

**Closed by cscharf** 2020-09-03 13:50 UTC
Labels: duplicate
