### ISSUE TITLE
Lock page logged in as email missing

### ISSUE THREAD

**Issue by runephilosof** [bitwarden/web#1699] opened 2022-05-20 07:23 UTC
### Steps To Reproduce

1. Log in
2. Wait for session timeout
3. On the lock page it says: "Logged in as __$1__ on bitwarden.com. "

### Expected Result

__$1__ should be replaced with my email

### Actual Result

It says __$1__

### Additional Context

Seems to an i18n problem on this line
https://github.com/bitwarden/web/blob/2ae98887b78be67fdc1f32166b17f3a9713e59ac/src/app/accounts/lock.component.html#L37

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2.28.1

**Comment by djsmith85** [comment] 2022-05-20 07:36
@runephilosof  Thank you for your report. This is a known issue and and a fix is target for the End of May release. Clicking on logout again, should bring you back to the expected screen.

Closing this as duplicate of https://github.com/bitwarden/web/issues/1557

**Closed by djsmith85** 2022-05-20 07:36 UTC
Labels: bug
