### ISSUE TITLE
Wrong text on login screen: "Logged in as __$1__ on bitwarden.com." and Unlocking not working

### ISSUE THREAD

**Issue by ponchofiesta** [bitwarden/web#1594] opened 2022-04-13 07:02 UTC
### Steps To Reproduce

Not sure if you can reproduce it but this is what I've done:

1. I was logged in on vault.bitwarden.com yesterday
2. I start the browser today and it reopens my Tabs.
3. This screen was shown on Bitwarden

### Expected Result

* A correct string is shown
* Vault unlocking should work

### Actual Result

* "Logged in as __$1__ on bitwarden.com." is shown
* When typing in my Password and click "Unlock", nothing happens.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/12248938/163118708-98540778-deb3-4844-a415-374f5517927e.png)

### Operating System

Windows

### Operating System Version

Windows 10 20H2

### Web Browser

Microsoft Edge

### Browser Version

Version 99.0.1150.55 (Offizielles Build) (64-Bit)

### Build Version

2.27.0

**Comment by ponchofiesta** [comment] 2022-04-13 07:05
Just say, that #1557 is the same.

**Comment by djsmith85** [comment] 2022-04-14 11:07
@ponchofiesta Thank you for the report. I'm closing this now as a duplicate of #1557

**Closed by djsmith85** 2022-04-14 11:07 UTC
Labels: bug
