### ISSUE TITLE
All Items can be treated as Trash and permanently deleted

### ISSUE THREAD

**Issue by KeithLRobertson** [bitwarden/web#1514] opened 2022-03-02 23:33 UTC
### Steps To Reproduce

1. Start with at least 3 items, 2 in Trash, 1 not. Each represents many items.
2. Click on Trash. See at least 2 items
3. Select one item in Trash.
4. Menu -> Permanently Delete Selected.
5. Confirm.

### Expected Result

Selected items are removed; only the remaining item(s) in Trash are shown and selectable in right side pane.

### Actual Result

Right side pane refreshes with All Items (aaaargh!) including those not in Trash, even though left side pane has only Trash selected.

It's very easy not to notice this to detrimental effect. I had 400+ entries and another 50 in Trash which I wanted to delete. Not knowing any better (I'm new to Bitwarden), I manually selected about half one-by-one and Permanently Deleted. Noticed Select All, so I clicked that. Left side still showed only Trash as highlighted, so I had no idea I was selecting everything in my vault!  Then I executed Permanently Delete Selected. Was shocked when every entry in my entire vault disappeared!

### Additional Context

May be similar to #1355. IMO this description is clearer.

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Firefox

### Browser Version

97.0.1

### Build Version

2.26.2

**Comment by Hinton** [comment] 2022-03-03 10:23
Duplicate of https://github.com/bitwarden/web/issues/1355

**Closed by Hinton** 2022-03-03 10:23 UTC
Labels: bug
