### ISSUE TITLE
Vault timeout locked showing __$1__ as logged in user

### ISSUE THREAD

**Issue by juanrapmc** [bitwarden/web#1645] opened 2022-05-08 08:46 UTC
### Steps To Reproduce

1. Login
2. Put computer to sleep (using windows) until vault gets locked
3. Go to BW tab

### Expected Result

 Logged in as myemail@domain.com on bitwarden.com. 

### Actual Result

 Logged in as __$1__ on bitwarden.com. 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/53954739/167288641-1aec26e2-194a-4416-9da0-b4f857b90a0a.png)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

100.0 (64-bit)

### Build Version

2.28.1

**Comment by juanrapmc** [comment] 2022-05-08 08:55
Similar happens if you go to https://vault.bitwarden.com/#/lock when logged out. Not sure if this is expected, I assume it should redirect to login screen when navigating to this endpoint (when not logged in)

**Comment by djsmith85** [comment] 2022-05-09 09:01
@juanrapmc Thank you for your report. This is a known issue and and a fix is target for the May release. Clicking on logout again, should bring you back to the expected screen.

Closing this as duplicate of https://github.com/bitwarden/web/issues/1557

**Closed by djsmith85** 2022-05-09 09:01 UTC
Labels: bug
