### ISSUE TITLE
Browser vault.bitwarden Darkmode Dropdown UI text is not visible

### ISSUE THREAD

**Issue by faizhameed** [bitwarden/web#1363] opened 2021-12-28 04:53 UTC
### Steps To Reproduce

1. Go to Tools
2. Click on Import Data
3. Select the format of import file

### Expected Result

Background color should be different to that of text.colour

### Actual Result

This issue is seen in dark mode view

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/41015883/147529278-f4c798bd-e64b-4a97-860f-a720b6f4b64e.png)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

NA

**Comment by alexaka1** [comment] 2022-01-02 15:51
Possible duplicate of #1338

**Comment by Hinton** [comment] 2022-01-10 11:06
Closed as a duplicate of #1338.

**Closed by Hinton** 2022-01-10 11:06 UTC
Labels: bug
