### ISSUE TITLE
Additional file format exports not showing up in dark mode 

### ISSUE THREAD

**Issue by Krychaz** [bitwarden/web#1361] opened 2021-12-26 14:31 UTC
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/ and make sure you're in dark mode 
2. Click on Tools -> Export vault
3. Try to select the additional file format export

### Expected Result

Expect result would give additional file formats to choose from, just like in the light theme:
![2021-12-26 14_22_28-Export Vault _ Bitwarden Web Vault - Brave](https://user-images.githubusercontent.com/36608718/147411162-2138dc31-7fce-408d-924f-84287c5bc569.png)

### Actual Result

While in dark mode, only one option shows up while the other two show up empty unless you hover on them:
![2021-12-26 14_22_56-Export Vault _ Bitwarden Web Vault - Brave](https://user-images.githubusercontent.com/36608718/147411182-447c103f-0d81-468a-bc27-62e150483783.png)

### Operating System

Windows

### Web Browser

Brave

### Browser Version

1.33

### Build Version

Chromium 96.0

**Comment by alexaka1** [comment] 2022-01-03 09:25
Possible duplicate of #1338

**Closed** 2022-01-10 11:04 UTC
Labels: bug
