### ISSUE TITLE
Memory usage while compiling is inordinately high

### ISSUE THREAD

**Issue by chris-morgan** [bitwarden/web#250] opened 2018-08-24 08:14 UTC
I just upgraded my self-hosted version of this, and it required over 1.7GB of memory to build. That seems inordinately much.

I operate a 1GB machine with no swap, and it tends to have almost 800MB of that free.

1.27.0 built successfully a month or two ago inside these constraints.

2.1.1, on the other hand, required me to add a full gigabyte of swap to make it work, and even that was perilously close to running out!

Whatever it’s doing while building, sure isn’t memory-efficient!

**Comment by peoro** [comment] 2018-08-24 11:16
I'm having the same issue.

It seems to be a problem with webpack.

**Comment by kspearrin** [comment] 2018-08-24 12:35
This project uses webpack4, while the others all use webpack 3. I guess there is some issue there.

**Comment by djsmith85** [comment] 2021-07-30 12:53
Hi @chris-morgan and @peoro, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2021-07-30 12:53 UTC
