### ISSUE TITLE
Improved error message when importing long notes from Lastpass

### ISSUE THREAD

**Issue by ssalonen** [bitwarden/web#194] opened 2018-03-26 18:33 UTC
To continue from discussion in the [community forums](https://community.bitwarden.com/t/improved-error-message-when-importing-long-notes-from-lastpass/490/3)

Hi all,

When importing long notes from lastpass, one might get the following error message

```
Ciphers[390].Notes: The field Notes must be a string with a maximum length of 10000. 
```

I understand that such long notes are not meant for bitwarden, see e.g. #50.

However, I would like to request that the UI would show what is the entry 390. It’s quite hard or almost impossible to match the CSV to the entries, especially in the case of multi-line entries like I have. 

The functionality as designed seem to work as intended, it’s just that the error messages could be better I think -- telling exactly what is the violating entry.

Best,
Sami

**Comment by birlorg** [comment] 2018-04-08 04:57
This also happens with 1pif formatted imports.

**Comment by kspearrin** [comment] 2018-08-02 12:59
I have adjusted the error message to be more clear in the next version.

**Comment by ssalonen** [comment] 2018-09-07 04:54
@kspearrin I can still see the same error message although new version (2.2.0) has been released since? Should the fix be already in?

**Comment by kspearrin** [comment] 2018-09-07 12:09
Yes, sorry, I confused this issue with another one. Reopened.

**Comment by gene1wood** [comment] 2019-01-06 22:59
It might be good to modify the title of this issue since this problem isn't related directly to Lastpass.

Or favor #102 over this as it's asking for the same thing, or close that as a duplicate of this.

Many people have reported this problem which I think highlights that the user experience here needs some improvement
* #151 mentions this issue but says it fails silently. When I encountered this it didn't fail silently, it showed an error window in red with error messages. #183 also mentions silent failure. Was this how it used to work and now we do at least have an error message?
* #201 calls this out as a Keepass2 exported content import issue, but this is really agnostic of the password manager the content is coming from. In my case it was from Lastpass which also allows notes on credentials and secure notes to exceed 10,000 characters encrypted
* #160 (and it's duplicate #248) and #216 contains comments asking for better UI around this as well
* #117 and #166 reports the problem back when the limit was 1000 intead of 10000 as does #45 when it was increased
* #162 suggests using file attachments
* #55 and #50 have the user also struggling with the confusing UI

Just looking at the number of users that encounter and report this problem, it's *5% of all the issues* reported here

In order to figure out which fields were causing the problem I ran this in python against the export file. The `6000` number is because the size limit is on the post-encryption size which is greater than the source size

```python
with open('lp.csv', 'rb') as csvfile:
    r = csv.reader(csvfile)
    for row in r:
        for record in row:
            if len(record) > 6000:
                print(','.join([x[:100] for x in row]))
```

After fixing it up and looking through GitHub issues I see indications that the number in the error message is the record number in the CSV with the issue. If this is the case, I'd recommend having the UI explicity indicate that's what the number is.

The UI for this error condition should give the user more information about what failed and what to do about it. Maybe display an excerpt of the field that exceeded the allowed length and instruct the user to go to their existing password manager and search for a record containing this excerpt and have them manually copy this content over into a [file attachment](https://help.bitwarden.com/article/attachments/) or something.

Or better yet, offer to do this for the user (convert a oversized field into a file attachment of a text file)

**Comment by ryancwalsh** [comment] 2019-01-23 19:00
I'm frustrated with LastPass and trying to convert to Bitwarden. So I created a Bitwarden account today and tried to migrate my LP data over. 

But now I'm getting this unhelpful error that everyone else seems to be complaining about too:

> An error has occurred. Ciphers[923]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

In looking at my CSV from LastPass, I have no idea what I need to fix.

So unfortunately it seems like I need to keep using LastPass.

If *I* can't figure out how to use Bitwarden, my parents *definitely* will not be able to.

**Comment by kspearrin** [comment] 2019-01-23 19:02
@ryancwalsh See https://help.bitwarden.com/article/import-data/#troubleshooting-import-errors

**Comment by ryancwalsh** [comment] 2019-01-23 19:07
@kspearrin That link is helpful in the sense that I didn't know about that article, but I agree with the 84 downvotes on it about it not actually solving my problem. 

It says:

> You can open the exported file in a text editor or spreadsheet program (such as Excel) to locate it. The offending item can be found at index X (as referenced in the error message) in the file. 

I don't know what "index 923" means, and I'm a software engineer (so certainly *most* people won't know what it means).

I've opened the CSV in Notepad++ and in Excel and can't figure out how to find the offending part(s).

Thanks for any suggestions.

**Comment by kspearrin** [comment] 2019-01-23 19:10
Each row in the import file is at a specific index. If viewing this in excel, index 923 would be at row 925 (0 offset + the header row).

**Comment by ryancwalsh** [comment] 2019-01-23 19:16
@kspearrin Thanks for your response! Unfortunately, line 925 is only 272 characters long, and all other lines near it are even shorter.

And none of those "lines" have line break characters. But I've noticed elsewhere throughout my LastPass CSV export (staring at the 19th entry) that certain entries include CR LF linebreaks.

But that's presumably normal for a LastPass export, so I don't know what I'm supposed to do at this point, especially since the error message is pointing me to an entry that seems totally normal and short.

**Comment by ssalonen** [comment] 2019-01-23 20:20
I agree with the above. As mentioned in my original description:

> It’s quite hard or almost impossible to match the CSV to the entries, especially in the case of multi-line entries like I have.

**Comment by ryancwalsh** [comment] 2019-01-23 22:59
@kspearrin  It seems to be related to this issue from 2016: https://github.com/bitwarden/web/issues/7#issuecomment-253301634

I've been importing entries in batches and have probably narrowed down the offenders to my LastPass Secure Notes (which mention `http://sn`).

I may have successfully imported all my other LastPass data but wonder how I'm supposed to import Secure Notes now.

And if the importer *cannot* support Secure Notes from LP, it would be great if it could exclude them gracefully and inform the user about how to import them separately.

**Comment by gene1wood** [comment] 2019-01-24 03:13
@ryancwalsh Until the messaging is improved, if you feel up to a little python, you can use [this code block in my comment above](https://github.com/bitwarden/web/issues/194#issuecomment-451783368) to identify records that are too long and are causing the problem. It's not that BitWarden can't deal with Secure Notes, it's that Secure Notes are the most likely types of records to exceed the 10000 character (after encryption) limit.

**Comment by ssalonen** [comment] 2019-02-17 15:10
I adapted python code example from @gene1wood to make a script that produces CSV that can be imported. The long notes are exported to individual files for manual importing.

```bash
$ python bitwarden_import.py
Too long secure note. Stored in lp_sec_note_0.txt


Finished Successfully!
Import lp_out.csv using bitwarden UI. Import lp_sec_note_XX.txt manually
```

`bitwarden_import.py`:
```python
from __future__ import print_function
import csv
import sys

with open('lp_in.csv', 'rb') as csvfile, \
	open('lp_out.csv', 'wb') as csvout:
	out = csv.writer(csvout)
	r = csv.reader(csvfile)
	columns = None	
	sec_note_index = 0
	for line_number, row in enumerate(r):
		# print(line_number)
		if not columns:
			columns = len(row)
			out.writerow(row)
			continue
		is_secure_note = row[0].startswith('http://sn')
		for record in row:
			if len(record) > 6000:
				if is_secure_note:
					fname = 'lp_sec_note_{}.txt'.format(sec_note_index)
					with open(fname, 'w') as f:
						f.write(row[3])
					print('Too long secure note. Stored in {}'.format(fname), file=sys.stderr)
					sec_note_index += 1
					break
				else:
					print('Too long entry: snippet' + ','.join([x[:100] for x in row]), file=sys.stderr)
					sys.exit(1)
		else:
			out.writerow(row)
```

**Comment by nlpsuge** [comment] 2019-05-26 07:40
Same issue. 

I'm very confused about this error message: 
Ciphers[X]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

I can not find the exact location of X in LibreOffice Calc.

**Comment by nlpsuge** [comment] 2019-05-26 08:08
But why can not I save more than 10000 characters in filed Notes?

**Comment by gardner** [comment] 2019-06-01 20:24
This has prevented me from moving over to Bitwarden for the last 1.5 years.

**Comment by robertoschwald** [comment] 2019-08-21 15:48
Currently evaluating Bitwarden Enterprise and this limitation hit me while importing a 1pif file. This limitation is not existing in Lastpass or 1Password, so for sure you are loosing business unless you lift this limitation. For sure I will not workaround my 1pif file (it has over 1000 entries...).

**Comment by Crocmagnon** [comment] 2019-08-22 12:42
Maybe long notes could automatically be imported as a text attachment if the account allows it ?

**Comment by nlpsuge** [comment] 2019-08-26 03:14
Hm, I believe attach long notes as attachment is not a good idea. Because It's no way to edit these long notes online. I have to download first.

**Comment by Crocmagnon** [comment] 2019-08-26 09:19
I agree but do you often edit a 10'000 characters long note? Or do you simply replace it with a new version? I'm curious about the use cases for such long fields, other than SSH/GPG keys.

**Comment by nlpsuge** [comment] 2019-08-30 09:41
I have several very long notes. Every note is relevant to a subject. Lastpass is also a good and secure note application in my view. But I want to look a none-commercial alternate.

**Comment by Crocmagnon** [comment] 2019-09-02 14:25
Thanks for the clarification 🙂 

> But I want to look a none-commercial alternate

Just to be picky on words: Bitwarden is commercial, but it's also open source and free ([as in free speech](https://en.wikipedia.org/wiki/Gratis_versus_libre)) where LastPass is a proprietary software. These are different things 😉
But we're getting off-topic.

IMHO Bitwarden should not be considered as a note application. There are other alternatives (free and open source) for this, like [Standard Notes](https://github.com/standardnotes/).
Bitwarden focuses on usernames/passwords, credit cards and short encrypted notes such as license numbers. You can also have attachments for things like GPG/SSH keys.

**Comment by gardner** [comment] 2019-09-03 01:24
@Crocmagnon that is the decision of the company to focus on whatever features they see fit. If they decide not to support large note fields, then the import process should import the _compatible_  data as best it can. I liked you original suggestion: 

> Maybe long notes could automatically be imported as a text attachment if the account allows it ?

This ticket is about increasing usability during the onboarding process. The onboarding process _should_ be as smooth as possible. Having a large gpg keypair in your LastPass should not prevent a normal person from importing their data into BitWarden. 

Perhaps finding more new users is not one of the current challenges that the 8bit team is dealing with.

**Comment by robertoschwald** [comment] 2019-09-03 04:12
Just lost business opportunities. Maybe some developers told the business guys „its not possible“. Happened so many times in the past.

**Comment by swishyswoosh** [comment] 2019-09-19 18:06
@gene1wood Thank you very much - that python snippet was super helpful, the output gave me the hints necessary to finally get my data imported from Lastpass. The import was choking on my saved gpg and ssh keys but the error message was practically useless in troubleshooting.  The devs clearly never tested import with multi-line secure notes - perhaps that should be added to the regression test suite.

**Comment by eliykat** [comment] 2021-02-23 23:59
We've now updated the import behaviour as follows:
* error message is now shown in a dialog so it doesn't disappear
* error message now contains the type and name for each problem item. (Assuming that you are using unique/reasonable names for your items)

(PR #841 )

There are some other good suggestions in this thread, but this covers the original issue identified by the OP so I'll close it. Requests to increase max string lengths etc. can be lodged as a [feature request](https://community.bitwarden.com/c/feature-requests/) on our forums.

**Closed by eliykat** 2021-02-23 23:59 UTC
Labels: enhancement
