### ISSUE TITLE
Attachments with long file names go beyond the window.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/web#695] opened 2020-11-09 12:57 UTC
## Describe the Bug
Long file names go beyond the visual boundary of the attachment window in the web vault.

## Steps To Reproduce
Log into your web vault and attach a file to a vault item.

## Expected Result
For the file name to wrap within the window.

## Actual Result
The file name goes beyond the window.

## Screenshots or Videos
![attachment](https://user-images.githubusercontent.com/73389600/98543620-aa203200-228a-11eb-8939-935d3a7c637e.png)

## Environment

- Operating system: Windows 10 Pro.
- Browser: Chrome Version 86.0.4240.183.
- Build Version (Bottom of the page): Version 2.16.2.

## Additional Context
N/A.

**Comment by gzachos** [comment] 2020-11-09 15:12
Thanks @SergeantConfused for creating this ticket.

This issue was initially encountered in the following environment:

- Operating system: Linux Mint 20
- Browser: Mozilla Firefox `82.0.2` (64-bit)
- Bitwarden Web Vault: `Version 2.16.2`

**Comment by mithileshz** [comment] 2020-11-10 22:50
hey, can I pick this up? I'm guessing the fix would be line wrapping for the text?

**Comment by kspearrin** [comment] 2020-11-11 02:03
Go for it. Should be a small css fix.

**Comment by mithileshz** [comment] 2020-11-12 15:32
Hey @kspearrin 
So there are two things here, when we upload a new file, the wrap is something like this in which the middle part of the file name is hidden. Should I follow the same approach here or should we display the full file name after it has been uploaded? Both examples in the image below
![image](https://user-images.githubusercontent.com/9119938/98960324-36855b80-24fc-11eb-8959-7b52fbf97490.png)

**Comment by gzachos** [comment] 2020-11-12 16:00
@mithileshz In my opinion, the full filename should be available before uploading. There can exist multiple files with long names which only differ in the middle portion. Uploading the wrong file, then removing it and then uploading the correct one will cause network/server traffic for no significant reason.

**Comment by kspearrin** [comment] 2020-11-12 16:10
I agree with @gzachos , but I am not sure if we can change the styling on the file input to wrap like that too?

**Comment by mithileshz** [comment] 2020-11-12 16:23
I'm not sure how that would happen as the <input> for the upload is doing the text wrapping in the case when you are uploading the file. I'll take a look if I can find a fix for it

**Comment by mithileshz** [comment] 2020-11-12 16:43
I had a look and the reason why it is being wrapped is width: 100% on the <input type="file"> from the class .form-control-file. As the button, the file name is part of the single input, you can either wrap it like in the screenshot above or make it full width (like the bug image above but instead during the upload). 

The way we can fix this is by hiding the input via CSS and wrapping it in a label and using that instead of the input. See https://stackoverflow.com/q/572768 and then using typescript to figure out the file name that we can display into a div below the input.

**Comment by kspearrin** [comment] 2020-11-12 18:08
I would rather use the native file input with its expected behavior.

**Comment by gzachos** [comment] 2020-11-16 23:26
I can see this bug is fixed in Web Vault Version `2.17.0`.

**Closed** 2020-12-15 21:03 UTC
