### ISSUE TITLE
Copy Verification Code menu item missing from OTP enabled entries on first login

### ISSUE THREAD

**Issue by kriskenn** [bitwarden/web#1420] opened 2022-01-31 13:47 UTC
### Steps To Reproduce

1. Log into the Bitwarden web vault.
2. Locate an entry that uses OTP and then click on the options menu (cog) to the right.
3. Note that "Copy Verification Code" does not appear as a menu item.
4. Click on the User menu at the top of the page and lock the vault (or refresh the page to do so).
5. Unlock the vault.
6. Locate the same entry used above and click on the options menu (cog) again.
7. Note that "Copy Verification Code" now appears as a menu item.

### Expected Result

"Copy Verification Code" option should appear below "Copy Password" upon first login.

### Actual Result

"Copy Verification Code" does not appear until the vault is locked and unlocked again.

### Screenshots or Videos

Entry options menu upon first login:
![NoCode](https://user-images.githubusercontent.com/94586761/151804412-77de1118-4cb1-43e5-ac62-12c2bdce3d30.png)

Entry options menu after locking and unlocking the vault/refreshing the page:
![Code](https://user-images.githubusercontent.com/94586761/151804474-b448f319-d081-4f31-ae3e-dc76b069a8a8.png)

### Operating System

Windows

### Operating System Version

Windows 11, OS Build 22000.469

### Web Browser

Microsoft Edge

### Browser Version

97.0.1072.76

### Build Version

2.25.1

**Comment by eliykat** [comment] 2022-02-03 07:29
The cause of this bug is explained here: https://github.com/bitwarden/web/pull/1277#discussion_r798230435 and should be fixed as part of PR #1277.

**Closed** 2022-02-10 23:48 UTC
Labels: bug
